using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Search;
using UnityEngine;
using UnityEngine.UIElements;
using static UnityEngine.Rendering.STP;

public class UICodeGenService
{
    public string GetGuid(ScriptableObject asset)
    {
        string path = AssetDatabase.GetAssetPath(asset);
        return AssetDatabase.AssetPathToGUID(path);
    }

    private static List<VisualElement> ExtractVisualElements(VisualElement root)
    {
        var result = new List<VisualElement>();
        var stack = new Stack<VisualElement>();

        foreach (VisualElement child in root.Children())
            stack.Push(child);

        while (stack.Count > 0)
        {
            VisualElement current = stack.Pop();
            result.Add(current);

            foreach (VisualElement child in current.Children())
                stack.Push(child);
        }

        return result;
    }

    private string SanitizeVariableName(string input)
    {
        StringBuilder result = new StringBuilder();
        bool upperNext = false;

        foreach (char c in input)
        {
            if (c == '-')
            {
                upperNext = true;
                continue;
            }

            if (upperNext)
            {
                result.Append(char.ToUpper(c));
                upperNext = false;
            }
            else
            {
                result.Append(c);
            }
        }

        return result.ToString();

    }

    private void GenerateInClassSpace(StringBuilder builder )
    {
        builder.AppendLine().AppendLine().AppendLine();
    }

    private void GenerateEditorGeneratedHeader(StringBuilder builder, string name)
    {
        builder.AppendLine("/****************************************************************************/")
               .AppendLine("// <auto-generated>")
               .AppendLine("// This file is autogenerated by UICodeGenService")
               .AppendLine($"// Unity Version:        {Application.unityVersion}")
               .AppendLine($"// .Net Runtime Version: {Environment.Version.ToString()}")
               .AppendLine($"// Framework Version:    {RuntimeInformation.FrameworkDescription}")
               .AppendLine("// ")
               .AppendLine("// Do not edit it manually")
               .AppendLine("// </auto-generated>")
               .AppendLine("/****************************************************************************/")
               .AppendLine("using System;")
               .AppendLine("using UnityEngine;")
               .AppendLine("using UnityEngine.UIElements;")
               .AppendLine("using UnityEditor;")
               .AppendLine()
               .AppendLine($"public partial class {name} : EditorWindow")
               .AppendLine("{");
    }


    private void GenerateEditorHeader(StringBuilder builder, string name)
    {
        builder.AppendLine("using System;")
               .AppendLine("using UnityEngine;")
               .AppendLine("using UnityEngine.UIElements;")
               .AppendLine("using UnityEditor;")
               .AppendLine()
               .AppendLine($"public partial class {name} : EditorWindow")
               .AppendLine("{");
    }


    private void GenerateGameplayGeneratedHeader(StringBuilder builder, string name)
    {
        builder.AppendLine("/****************************************************************************/")
               .AppendLine("// <auto-generated>")
               .AppendLine("// This file is autogenerated by UICodeGenService")
               .AppendLine($"// Unity Version:        {Application.unityVersion}")
               .AppendLine($"// .Net Runtime Version: {Environment.Version.ToString()}")
               .AppendLine($"// Framework Version:    {RuntimeInformation.FrameworkDescription}")
               .AppendLine("// ")
               .AppendLine("// Do not edit it manually")
               .AppendLine("// </auto-generated>")
               .AppendLine("/****************************************************************************/")
               .AppendLine("using System;")
               .AppendLine("using UnityEngine;")
               .AppendLine("using UnityEngine.UIElements;")
               .AppendLine()
               .AppendLine("[RequireComponent(typeof(UIDocument))]")
               .AppendLine($"public partial class {name} : MonoBehaviour")
               .AppendLine("{");
    }


    private void GenerateGameplayHeader(StringBuilder builder, string name)
    {
        builder.AppendLine("using System;")
               .AppendLine("using UnityEngine;")
               .AppendLine("using UnityEngine.UIElements;")
               .AppendLine()
               .AppendLine("[RequireComponent(typeof(UIDocument))]")
               .AppendLine($"public partial class {name} : MonoBehaviour")
               .AppendLine("{");
    }

    private void GenerateEditorConstants(StringBuilder builder, VisualTreeAsset uxml, StyleSheet[] ussStyleSheets, IEnumerable<VisualElement> visualElements)
    {
        var pattern = @"Window|Editor";
        var uxmlName = Regex.Replace(uxml.name, pattern, "", RegexOptions.IgnoreCase);
        uxmlName = Regex.Replace(uxmlName, "(?<!^)([A-Z])", " $1");

        builder.AppendLine("\t/*************************************************************************/")
               .AppendLine("\t#region Constants")
               .AppendLine("\t/*************************************************************************/")
               .AppendLine($"\tprivate const string UxmlGUID = \"{GetGuid(uxml)}\";")
               .AppendLine($"\tprivate const string UxmlName = \"{uxmlName}\";");
        //foreach (var uss in ussStyleSheets)
        //{
        //    builder.AppendLine($"    private const string {char.ToUpper(uss.name[0])}{uss.name.Substring(1)}UssGUID = \"{GetGuid(uss)}\";");
        //}

        foreach (var elem in visualElements)
        {
            if (string.IsNullOrWhiteSpace(elem.name)) continue;
            var sanitizedName = SanitizeVariableName(elem.name);
            builder.AppendLine($"\tprivate const string ElementName_{char.ToUpper(sanitizedName[0])}{sanitizedName.Substring(1)} = \"{elem.name}\";");
        }
        builder.AppendLine("\t#endregion");
        builder.AppendLine("\t/*************************************************************************/");
    }

    private void GenerateGameplayConstants(StringBuilder builder, IEnumerable<VisualElement> visualElements)
    {
        builder.AppendLine("\t/*************************************************************************/")
               .AppendLine("\t#region Constants")
               .AppendLine("\t/*************************************************************************/");

        foreach (var elem in visualElements)
        {
            if (string.IsNullOrWhiteSpace(elem.name)) continue;
            var sanitizedName = SanitizeVariableName(elem.name);
            builder.AppendLine($"\tprivate const string ElementName_{char.ToUpper(sanitizedName[0])}{sanitizedName.Substring(1)} = \"{elem.name}\";");
        }
        builder.AppendLine("\t#endregion");
        builder.AppendLine("\t/*************************************************************************/");
    }

    private void GenerateEditorFields(StringBuilder builder, IEnumerable<VisualElement> visualElements)
    {
        builder.AppendLine("\t/*************************************************************************/")
               .AppendLine("\t#region Fields")
               .AppendLine("\t/*************************************************************************/");

        foreach (var elem in visualElements)
        {
            if (string.IsNullOrWhiteSpace(elem.name)) continue;

            builder.Append("\tprivate ")
                   .Append(elem.GetType().Name)
                   .Append(" _")
                   .Append(SanitizeVariableName(elem.name))
                   .AppendLine(" = null;");
        }

        builder.AppendLine()
               .AppendLine("\t[SerializeField]")
               .AppendLine("\tprivate VisualTreeAsset _uxml = null;");

        builder.AppendLine("\t#endregion")
               .AppendLine("\t/*************************************************************************/");
    }

    private void GenerateGameplayFields( StringBuilder builder, IEnumerable<VisualElement> visualElements)
    {
        builder.AppendLine("\t/*************************************************************************/")
               .AppendLine("\t#region Fields")
               .AppendLine("\t/*************************************************************************/");

        foreach (var elem in visualElements)
        {
            if (string.IsNullOrWhiteSpace(elem.name)) continue;

            builder.Append("\tprivate ")
                   .Append(elem.GetType().Name)
                   .Append(" _")
                   .Append(SanitizeVariableName(elem.name))
                   .AppendLine(" = null;");
        }

        builder.AppendLine()
               .AppendLine("\t[SerializeField]")
               .AppendLine("\tprivate UIAssetConfig _config = null;")
               .AppendLine()
               .AppendLine("\t[SerializeField]")
               .AppendLine("\tprivate PanelSettings _panelSettings = null;")
               .AppendLine()
               .AppendLine("\t[SerializeField]")
               .AppendLine("\tprivate VisualTreeAsset _uxml = null;")
               .AppendLine()
               .AppendLine("\t[SerializeField]")
               .AppendLine("\tprivate VisualElement _rootVisualElement = null;")
               .AppendLine()
               .AppendLine("\t[SerializeField]")
               .AppendLine("\tprivate UIDocument _uiDoc = null;");

        builder.AppendLine("\t#endregion")
               .AppendLine("\t/*************************************************************************/");
    }

    private void GenerateLoadAssetsEditorFunction(StringBuilder builder)
    {
        builder.AppendLine("\tprivate void LoadAssets()")
               .AppendLine("\t{")
               .AppendLine("\t\tvar path = string.Empty;")
               .AppendLine("\t\tif (_uxml == null)")
               .AppendLine("\t\t{")
               .AppendLine("\t\t\tpath = AssetDatabase.GUIDToAssetPath(UxmlGUID);")
               .AppendLine("\t\t\t_uxml = AssetDatabase.LoadAssetAtPath<VisualTreeAsset>(path);")
               .AppendLine("\t\t}")
               .AppendLine("\t}");

    }

    private void GenerateLoadAssetsGameplayFunction(StringBuilder builder, string name)
    {
        builder.AppendLine("\tprivate void LoadAssets()")
               .AppendLine("\t{")
               .AppendLine("\t\tif (_config == null)")
               .AppendLine($"\t\t\t_config = Resources.Load<UIAssetConfig>(\"Scriptables/{name}\");")
               .AppendLine()
               .AppendLine("\t\tif (_panelSettings == null && _config.HasPanelSettings)")
               .AppendLine("\t\t\t_panelSettings = _config.PanelSettings;")
               .AppendLine()
               .AppendLine("\t\tif (_panelSettings == null)")
               .AppendLine("\t\t\tthrow new InvalidOperationException(\"Unable to load Panel Settings.\");")
               .AppendLine()
               .AppendLine("\t\tif (_uxml == null && _config.HasUxml)")
               .AppendLine($"\t\t\t_uxml = _config.Uxml;")
               .AppendLine()
               .AppendLine("\t\tif (_uxml == null)")
               .AppendLine("\t\t\tthrow new InvalidOperationException(\"Unable to load UXML.\");")
               .AppendLine("\t}");
    }
    private void GenerateRequireEditorMethod(StringBuilder builder)
    {
        builder.AppendLine("\tprivate T Require<T>(string name) where T : VisualElement")
               .AppendLine("\t{")
               .AppendLine("\t\tvar elem = rootVisualElement.Q<T>(name);")
               .AppendLine("\t\tif (elem == null)")
               .AppendLine("\t\t\tthrow new InvalidOperationException($\"Required UI element '{name}' of type Button was not found.\");")
               .AppendLine()
               .AppendLine("\t\treturn elem;")
               .AppendLine("\t}");
    }
    private void GenerateRequireGameplayMethod(StringBuilder builder)
    {
        builder.AppendLine("\tprivate T Require<T>(string name) where T : VisualElement")
               .AppendLine("\t{")
               .AppendLine("\t\tvar elem = _rootVisualElement.Q<T>(name);")
               .AppendLine("\t\tif (elem == null)")
               .AppendLine("\t\t\tthrow new InvalidOperationException($\"Required UI element '{name}' of type Button was not found.\");")
               .AppendLine()
               .AppendLine("\t\treturn elem;")
               .AppendLine("\t}");
    }

    private void GenerateInitializeComponentsEditorFunction(StringBuilder builder, IEnumerable<VisualElement> visualElements)
    {
        builder.AppendLine("\tprotected void InitializeComponents()")
               .AppendLine("\t{")
               .AppendLine("\t\tLoadAssets();")
               .AppendLine()
               .AppendLine("\t\t_uxml.CloneTree(rootVisualElement);")
               .AppendLine();

        foreach (var elem in visualElements)
        {
            if (string.IsNullOrWhiteSpace(elem.name)) continue;

            var sanitizedName = SanitizeVariableName(elem.name);
            builder.AppendLine($"\t\t_{SanitizeVariableName(elem.name)} = Require<{elem.GetType().Name}>(ElementName_{char.ToUpper(sanitizedName[0])}{sanitizedName.Substring(1)});");
        }


        builder.AppendLine("}");
    }

    private void GenerateInitializeComponentsGameplayFunction(StringBuilder builder, IEnumerable<VisualElement> visualElements)
    {
        builder.AppendLine("\tprotected void InitializeComponents()")
               .AppendLine("\t{")
               .AppendLine("\t\tLoadAssets();")
               .AppendLine()
               .AppendLine("\t\tif(_uiDoc == null) _uiDoc = GetComponent<UIDocument>();")
               .AppendLine()
               .AppendLine("\t\t_rootVisualElement = _uiDoc.rootVisualElement;")
               .AppendLine("\t\t_uiDoc.panelSettings = _panelSettings;")
               .AppendLine("\t\t_uiDoc.visualTreeAsset = _uxml;")
               .AppendLine("\t\t_uxml.CloneTree(_rootVisualElement);")
               .AppendLine();

        foreach (var elem in visualElements)
        {
            if (string.IsNullOrWhiteSpace(elem.name)) continue;

            var sanitizedName = SanitizeVariableName(elem.name);
            builder.AppendLine($"\t\t_{SanitizeVariableName(elem.name)} = Require<{elem.GetType().Name}>(ElementName_{char.ToUpper(sanitizedName[0])}{sanitizedName.Substring(1)});");
        }


        builder.AppendLine("}");
    }

    private void GenerateShowWindowFunction(StringBuilder builder, string name)
    {
        builder.AppendLine($"\t[MenuItem(\"Tools/{name}\")]")
               .AppendLine("\tpublic static void OpenWindow()")
               .AppendLine("\t{")
               .AppendLine($"\t\tvar wnd = GetWindow<{name}>();")
               .AppendLine("\t\twnd.titleContent = new(UxmlName);")
               .AppendLine("\t\twnd.Show();")
               .AppendLine("\t}");
    }
    
    public void GenerateCreateGUIFunction(StringBuilder builder)
    {
        builder.AppendLine("\tprivate void CreateGUI()")
               .AppendLine("\t{")
               .AppendLine("\t\tInitializeComponents();")
               .AppendLine("\t}");
    }

    public void GenerateAwakeFunction(StringBuilder builder)
    {
        builder.AppendLine("\tprivate void Awake()")
               .AppendLine("\t{")
               .AppendLine("\t\tInitializeComponents();")
               .AppendLine("\t}");
    }

    private static void EnsureFolderExists(string folderPath)
    {
        var folders = folderPath.Split('/');
        var currentFolder = folders[0]; // Assets

        for (var i = 1; i < folders.Length; i++)
        {
            var nextFolder = $"{currentFolder}/{folders[i]}";

            if (!AssetDatabase.IsValidFolder(nextFolder))
            {
                AssetDatabase.CreateFolder(currentFolder, folders[i]);
            }

            currentFolder = nextFolder;
        }
    }


    private void WriteFile(StringBuilder builder, string fileName, string relativePath, string suffix)
    {
        if (string.IsNullOrWhiteSpace(fileName) || string.IsNullOrWhiteSpace(relativePath)) return;

        var fullName = $"{fileName}.{suffix}";
        var dirPath = $"{Application.dataPath}/{relativePath}/";
        var filePath = $"{dirPath}{fullName}";

        if (!Directory.Exists(dirPath)) Directory.CreateDirectory(dirPath);

        File.WriteAllText(filePath, builder.ToString(), Encoding.UTF8);
    }

    public void GenerateEditorFile(VisualTreeAsset uxml)
    {

        //if (!uxmlField.value || uxmlField.GetType() != typeof(VisualTreeAsset)) return;

        //var uxml = uxmlField.value as VisualTreeAsset;
        var ussStyleSheets = uxml.stylesheets.ToArray();

        var root = uxml.Instantiate();
        var visualElements = ExtractVisualElements(root);

        var builder = new StringBuilder();
        GenerateEditorGeneratedHeader(builder, uxml.name);
        GenerateEditorConstants(builder, uxml, ussStyleSheets, visualElements);
        GenerateInClassSpace(builder);
        GenerateEditorFields(builder, visualElements);
        GenerateInClassSpace(builder);
        GenerateLoadAssetsEditorFunction(builder);
        builder.AppendLine();
        GenerateShowWindowFunction(builder, uxml.name);
        builder.AppendLine();
        GenerateRequireEditorMethod(builder);
        builder.AppendLine();
        GenerateInitializeComponentsEditorFunction(builder, visualElements);

        builder.AppendLine("}");

        WriteFile(builder, uxml.name, "Editor/UI/generated", "generated.cs");


        builder.Clear();


        if (!File.Exists($"{Application.dataPath}/Editor/Scriptables/{uxml.name}.asset"))
        {

            var scriptableFolderPath = $"Assets/Editor/Scriptables/";


            EnsureFolderExists(scriptableFolderPath);


            var assetConfig = ScriptableObject.CreateInstance<UIAssetConfig>();
            assetConfig.Uxml = uxml;
            assetConfig.PanelSettings = Resources.Load<PanelSettings>("UI/Panel Settings/RuntimePanelSettings");

            var scriptableAssetPath = $"{scriptableFolderPath}{uxml.name}.asset";


            AssetDatabase.CreateAsset(assetConfig, scriptableAssetPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Selection.activeObject = assetConfig;

            Debug.Log($"Created: {scriptableAssetPath}");
        }

        if (File.Exists($"{Application.dataPath}/Editor/UI/{uxml.name}.cs")) return;

        GenerateEditorHeader(builder, uxml.name);
        GenerateCreateGUIFunction(builder);
        builder.AppendLine("}");

        WriteFile(builder, uxml.name, "Editor/UI", "cs");

        builder.Clear();
    }


    public void GenerateGameplayFile(VisualTreeAsset uxml)
    {
        var ussStyleSheets = uxml.stylesheets.ToArray();

        var root = uxml.Instantiate();
        var visualElements = ExtractVisualElements(root);

        var builder = new StringBuilder();
        GenerateGameplayGeneratedHeader(builder, uxml.name);
        GenerateGameplayConstants(builder, visualElements);
        GenerateInClassSpace(builder);
        GenerateGameplayFields(builder, visualElements);
        GenerateInClassSpace(builder);
        GenerateLoadAssetsGameplayFunction(builder, uxml.name);
        builder.AppendLine();
        GenerateRequireGameplayMethod(builder);
        builder.AppendLine();
        GenerateInitializeComponentsGameplayFunction(builder, visualElements);

        builder.AppendLine("}");

        WriteFile(builder, uxml.name, "Scripts/UI/generated", "generated.cs");

        builder.Clear();

        if (!File.Exists($"{Application.dataPath}/Resources/Scriptables/{uxml.name}.asset"))
        {

            var scriptableFolderPath = $"Assets/Resources/Scriptables/";


            EnsureFolderExists(scriptableFolderPath);


            var assetConfig = ScriptableObject.CreateInstance<UIAssetConfig>();
            assetConfig.Uxml = uxml;
            assetConfig.PanelSettings = Resources.Load<PanelSettings>("UI/Panel Settings/RuntimePanelSettings");
             
            var scriptableAssetPath = $"{scriptableFolderPath}{uxml.name}.asset";


            AssetDatabase.CreateAsset(assetConfig, scriptableAssetPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Selection.activeObject = assetConfig;

            Debug.Log($"Created: {scriptableAssetPath}");
        }

        if (File.Exists($"{Application.dataPath}/Scripts/UI/{uxml.name}.cs")) return;

        GenerateGameplayHeader(builder, uxml.name);
        GenerateAwakeFunction(builder);
        builder.AppendLine("}");

        WriteFile(builder, uxml.name, "Scripts/UI", "cs");

        builder.Clear();
    }
}
